# Trying different themes
# Another theme that is interesting is minimal
remote_theme: pages-themes/slate@v0.2.0

title: [Filippo Guerra Statistic's website]
description: [A website to answer statistic's homeworks]
